# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df722b85bb4188e964c24452579815ae2843b775fb9b3ade7ebf3916888b088812cebd2cfdf5bb0a097ab19c564c80f1ef311547a200f1d88453d524a1c03654

test:
  secret_key_base: b81272979c615b9534df39a634e8780d4545a40e7bb57e2d5430dcdca60efece7b3a95569dfd51de30b574e64e6539ba99d7578b06090e4520e4eb3a413a98ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
